[theme]
backgroundColor = '#022252'
base = "dark"

# Primary accent for interactive elements
primaryColor = '#F36295'

# Color used for almost all text
textColor = '#03080C'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
